### PR TITLE
Use transpiled lib directory as main entrypoint

### LINKED ISSUE #8: Unexpected token import
When I import any of the validators from redux-form-validators into my component, I get the following error 

Uncaught SyntaxError: Unexpected token import

Which points somewhere here 
```
/*!**********************************************!*\
  !*** ./~/redux-form-validators/src/index.js ***!
  \**********************************************/
/***/ function(module, exports) {

	import absence from './absence'
	import acceptance from './acceptance'
	import addValidator from './add-validator'
	import confirmation from './confirmation'
```

Anyone else facing this issue? I am using CRA, redux form validators version 2.0.0

### PR DESCRIPTION
**Pull request by benbarber**
This fixes the issue #8

### CODE REVIEW

**Comment by tmartensen** [comment]
@gtournie are you going to punch out a release for this?

**Comment by gtournie** [comment]
@benbarber's PR has been merged ;)

**Comment by terenced** [comment]
@gtournie can you please cut a new release so that it includes this fix?

**Comment by gtournie** [comment]
done

**Pull request merged**
