### PR TITLE
Added Typescript definitions for validators

### PR DESCRIPTION
**Pull request by benbarber**
I have added some Typescript definitions for the available validators. I have been using these definitions in a few projects recently and it would be great if they could be merged in.

### CODE REVIEW

**Comment by vkhv** [comment]
++++

**Comment by sanex3339** [comment]
This definitions is not correct. With this definitions i cant use validators in a array.

```validate={[required(), format()]} // <- type error```

**Comment by burtek** [comment]
Any progress on this PR?

**Comment by gtournie** [comment]
As @sanex3339 said, these definitions need to be fixed:
- `...(options?: DefaultValidatorOptions) => Validator | Validator[]` Why Validator[]? I don't see when a validator could return an array of validators...?
- `msg` & `message` can be FormatMessage Elements (from react-intl) or Objects (`msg: { tooShort: '...' }`)
- file: `minSize` & `maxSize` can also be numbers (representing bytes)
- date: all comparators can also be numbers (timestamps)

**Comment by burtek** [comment]
I also noticed `Validators` is not exported due to which it is currently impossible to [override default messages](https://www.npmjs.com/package/redux-form-validators#default-messages-override) if not using `react-intl`

**Comment by benbarber** [comment]
Thanks for the feedback and sorry for the delay with this PR, I will have some time to get it updated this week.

The `Validator | Validator[]` definition mirrors the type that's specified in the Redux Form definitions. I can take the array definition out as it's not used at all here.

**Comment by sanex3339** [comment]
Anyway, `Validator | Validator[]` is wrong.

**Comment by burtek** [comment]
@benbarber 

> The Validator | Validator[] definition mirrors the type that's specified in the Redux Form definitions

It means, that Redux Form accepts either a Validator or an array of Validators. But one validator is just a Validator.

**Comment by gtournie** [comment]
@burtek 
> I also noticed there is no messages exported due to which it is currently impossible to override default messages if not using react-intl
These feature is covered by tests. If there is a bug, can you open a new issue and give me a way to reproduce it please? Also, it's been released since 2.3.0, so please check your version.

**Comment by benbarber** [comment]
@sanex3339 @gtournie @burtek I have addressed all of your feedback and requests so this PR is ready for review again.

**Comment by gtournie** [comment]
Good job @benbarber! Just a few more things:
- MessageDescriptor: can also be { props: MessageDescriptor } => FormattedMessage
- MessageDescriptor: id is not required
- formatMessage: doesn't accept a string as argument
- formatSize: size is always a string
- pluralRules: must be an object

**Comment by benbarber** [comment]
@gtournie thanks for you feedback, this PR has been updated with it now.

**Comment by benbarber** [comment]
Each message is now a type of ValidatorMessage which can be any one of `MessageDescriptor | MessageProps | string`.

**Comment by burtek** [comment]
@gtournie any chance this would get merged soon?

**Comment by eideer** [comment]
Is/should there be - a type definition for the `addValidator` options as well?

**Comment by benbarber** [comment]
@gtournie no problem, I will get that added for you

**Pull request merged**
