### PR TITLE
Updated url validator regex to support 127.0.0.1 and localhost if option is present

### LINKED ISSUE #26: url doesn't accept http://localhost or http://127.0.0.1
title says it all

### PR DESCRIPTION
**Pull request by bsears90**
Removed the IP exclusion on local/private networks from the regex , fixes half of #26

### CODE REVIEW

**Comment by gtournie** [comment]
@bsears90 thanks for the PR but I think the best way to handle that would be through an option. This way it wouldn't break the backward compatibility

**Comment by bsears90** [comment]
@gtournie I added an option called "allowLocal" which if present will switch the regex to one that supports 127.0.0.1 and localhost

**Comment by bsears90** [comment]
@gtournie can you review and merge?

**Comment by airen29** [comment]
@gtournie  Any update? Thanks

**Comment by gtournie** [comment]
@airen29 I'm working on it. Should be done soon

**Comment by gtournie** [comment]
Fixed with version 3.0.0

**Pull request closed without merging**
