### PR TITLE
use different "is not an integer" message for int: true

### LINKED ISSUE #23: numericality({int: true}) should say "not an integer" for floating point values like "1.5"
Right now it says "not a number", which users will think is a bug since 1.5 is clearly a number.

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #23

### CODE REVIEW

**Comment by jedwards1211** [comment]
@gtournie poke

**Comment by gtournie** [comment]
@jedwards1211 I'm not sure about replacing the message [when the validator requires an integer and the user doesn't enter a number](https://github.com/gtournie/redux-form-validators/pull/24/files#diff-c668daac64d3045e0ec75ed31e7b1b1bR32)... I would rather keep the "is not a number" message in that case, even if it means the user have to fill the form in 2 steps. I'm just not sure that the word "integer" is a commonly understood term

**Comment by jedwards1211** [comment]
@gtournie well I think we need to come up with something that's commonly understood like "must be a whole number".  Imagine if you've entered "2.3" and the form tells you "is not a number."  Wouldn't you be thinking, "that's nonsense, of course 2.3 is a number!"  I think most users would be confused for awhile before they figure out what the program is asking for.

At the very least, are you open to using a separate `form.errors.notAnInteger` ID, even if the default message is still "is not a number"?  With that it we could set the default error message for `int: true` to whatever we want (like "must be a whole number") instead of having to pass it into every place where we use `int: true` or create a wrapper function for `numericality` to do that.

**Comment by gtournie** [comment]
@jedwards1211 I'm ok to use a separate `form.errors.notAnInteger` message. I just feel like it should be better to not use this message in case it's not a number/float number (like the highlighted line in my link suggested it).
What I'd like to avoid is to display "is not an integer" in case the user typed "abc". 
Basically, something like:
1. the input is not a number => message "is not a number"
2. the input is a number but not an integer (a float) => message "is not an integer"
```
if (!isNumber(value)) {
  // Can't be a number (or a float number).
  return Validators.formatMessage(prepareMsg(msg, 'notANumber')
}
if (int && (+value % 1)) {
  // Return only this message if it's a float number and the "int" option is set
  return Validators.formatMessage(prepareMsg(msg, 'notAnInteger'))
}
```
I'm not really ok to use "whole number" though, it wouldn't be correct and could be confusing. For example: -5 is an integer but not a whole number.

**Comment by jedwards1211** [comment]
Oh I see your point about the highlighted line, that makes sense.  And yes it's kind of unfortunate that "whole number" technically means an integer greater than zero.  Maybe "round number" would be a clear enough colloquial term, but unfortunately it too has a special meaning in mathematics.

**Comment by gtournie** [comment]
I think we should keep 'is not an integer' for now. It'll only be displayed if the user enters a float number.

**Comment by jedwards1211** [comment]
@gtournie oh okay.  I'll make that change

**Comment by jedwards1211** [comment]
@gtournie okay, should be ready when the CI passes

**Comment by gtournie** [comment]
Also, could you rebase your PR to get just one commit please?

**Comment by jedwards1211** [comment]
Oh, sorry I missed your message, I would have been happy to do that.  Thanks!

**Pull request merged**
